# Generated by Django 5.2.4 on 2025-07-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieMate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
